---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: fedora-01
    image: bossjones/fedora24-systemd-ansible:latest
    privileged: True
    command: /usr/sbin/init
    # run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    # init: /usr/lib/systemd/systemd
    groups:
      - fedora
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
